/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.7/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    java
    application
    idea
}

repositories {
    // Use JCenter for resolving dependencies.
    jcenter()
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter API for testing.
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.6.2")

    // Use JUnit Jupiter Engine for testing.
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:29.0-jre")

    // jpa
    implementation("org.hibernate:hibernate-entitymanager:5.4.27.Final")

    // h2
    implementation("com.h2database:h2:1.4.200")

    // querydsl
    implementation("com.querydsl:querydsl-jpa:4.4.0")
    implementation("com.querydsl:querydsl-apt:4.4.0")
    //implementation("org.slf4j:slf4j-log4j12:2.0.0-alpha1")
    //annotationProcessor("com.querydsl:querydsl-apt:4.4.0")
    //annotationProcessor("org.slf4j:slf4j-log4j12:2.0.0-alpha1")
}

application {
    // Define the main class for the application.
    mainClass.set("jpabook.App")
}

tasks.test {
    // Use junit platform for unit tests.
    useJUnitPlatform()
}

tasks.register("generateQueryDSL") {
    typeOf<JavaCompile>()
    setGroup("build")
}

tasks.compileJava {
    dependsOn("generatedQueryDSL")
}

sourceSets {
    main {
        java {
            srcDir("src/main/java/generated")
        }
    }
}