logging:
  level:
    root: "warn"
    org.springframework.web: "debug"
    org.hibernate: "error"

spring:
  banner:
    image:
      location: banner.png
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.H2Dialect"
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: create
  datasource:
    url: "jdbc:h2:tcp://localhost/~/jpabook"
    username: "sa"
    password: ""
  session:
    store-type: jdbc